// Next Token Explorer — Autoregressive Token Prediction Visualizer
// ------------------------------------------------------------
// Backend for an educational tool that exposes the autoregressive
// decoding process of transformer-based language models. At each
// decoding step, the model produces a logit vector over its vocabulary;
// softmax converts logits to probabilities; a sampling strategy
// (temperature-controlled) selects the next token. This server
// retrieves the log-probability distributions (logprobs) at each
// step so the frontend can visualize token-by-token generation.
//
// Supports OpenAI, LM Studio, and Ollama as providers.
// Uses each provider's native API for logprobs support:
//   - OpenAI: /v1/chat/completions (logprobs supported)
//   - LM Studio: /v1/responses (Open Responses spec — /v1/chat/completions silently ignores logprobs)
//   - Ollama: /api/chat (native API, logprobs supported since v0.12.11)
// All configuration is passed per-request from the frontend.
// Nothing is stored on disk.

const fs = require('fs');
const path = require('path');
const express = require('express');
const OpenAI = require('openai');

const app = express();
const port = process.env.PORT || 3000;

// Environment API key is used as a convenience default — never written to disk
const envOpenAIKey = process.env.OPENAI_API_KEY || '';

// Load pre-scanned model support data if available (generated by scan-models.js)
// Reads both supported.json (final output) and scan-history.json (live updates
// written after each probe, so results are available while a scan is in progress).
const SUPPORTED_JSON_PATH = path.join(__dirname, 'supported.json');
const HISTORY_JSON_PATH = path.join(__dirname, 'scan-history.json');

function loadSupportedModels() {
  let supported = null;
  let history = null;

  try {
    if (fs.existsSync(SUPPORTED_JSON_PATH)) {
      supported = { data: JSON.parse(fs.readFileSync(SUPPORTED_JSON_PATH, 'utf8')), mtime: fs.statSync(SUPPORTED_JSON_PATH).mtimeMs };
    }
  } catch (err) {
    console.warn('Could not read supported.json:', err.message);
  }

  try {
    if (fs.existsSync(HISTORY_JSON_PATH)) {
      history = { mtime: fs.statSync(HISTORY_JSON_PATH).mtimeMs };
    }
  } catch {}

  // If history is newer than supported.json (scan in progress), use history
  if (history && (!supported || history.mtime > supported.mtime)) {
    const fromHistory = buildFromHistory();
    if (fromHistory) return fromHistory;
  }

  return supported?.data || null;
}

function buildFromHistory() {
  try {
    if (!fs.existsSync(HISTORY_JSON_PATH)) return null;
    const history = JSON.parse(fs.readFileSync(HISTORY_JSON_PATH, 'utf8'));
    const entries = Object.values(history.models || {});
    if (entries.length === 0) return null;

    const supported = entries.filter((m) => m.logprobs_supported);
    const unsupported = entries.filter((m) => !m.logprobs_supported);

    return {
      scanned_at: new Date().toISOString(),
      source: 'scan-history.json',
      total_scanned: entries.length,
      total_supported: supported.length,
      total_unsupported: unsupported.length,
      supported,
      unsupported,
    };
  } catch (err) {
    console.warn('Could not read scan-history.json:', err.message);
    return null;
  }
}

app.use(express.json());
app.use(express.static(path.join(__dirname)));

function logprobToProbability(logprob) {
  return Math.exp(logprob);
}

function normalizeTokenEntry(entry) {
  return {
    token: entry?.token ?? '',
    logprob: entry?.logprob,
    probability:
      typeof entry?.logprob === 'number' ? logprobToProbability(entry.logprob) : null,
    top_alternatives: (entry?.top_logprobs || [])
      .map((alt) => ({
        token: alt?.token ?? '',
        logprob: alt?.logprob,
        probability:
          typeof alt?.logprob === 'number' ? logprobToProbability(alt.logprob) : null,
      }))
      .sort((a, b) => (b.probability ?? -Infinity) - (a.probability ?? -Infinity)),
  };
}

// Resolve the base URL (without /v1 suffix) for direct HTTP calls
function resolveBaseOrigin(providerConfig) {
  const { provider, baseUrl } = providerConfig || {};
  const defaults = {
    lmstudio: 'http://localhost:1234',
    ollama: 'http://localhost:11434',
  };
  if (baseUrl) {
    // Strip trailing /v1 or /v1/ if present so we can build native paths
    return baseUrl.replace(/\/v1\/?$/, '');
  }
  return defaults[provider] || defaults.lmstudio;
}

// Build an OpenAI-compatible client (used for OpenAI and LM Studio)
function makeClient(providerConfig) {
  const { provider, apiKey, baseUrl } = providerConfig || {};

  if (provider === 'openai') {
    const key = apiKey || envOpenAIKey;
    if (!key) throw new Error('OpenAI API key is required. Paste it in the settings panel or set OPENAI_API_KEY env var.');
    return new OpenAI({ apiKey: key });
  }

  // LM Studio exposes an OpenAI-compatible endpoint
  const defaults = {
    lmstudio: 'http://localhost:1234/v1',
    ollama: 'http://localhost:11434/v1',
  };
  const url = baseUrl || defaults[provider] || defaults.lmstudio;
  return new OpenAI({ apiKey: 'not-needed', baseURL: url });
}

// --- Ollama native API helpers ---

async function ollamaChatWithLogprobs({ origin, model, prompt, messages, temperature, top_logprobs, max_output_tokens, seed, top_p, repeat_penalty, stop }) {
  const url = `${origin}/api/chat`;
  const options = {
    temperature,
    num_predict: max_output_tokens,
  };
  if (typeof seed === 'number') options.seed = seed;
  if (typeof top_p === 'number') options.top_p = top_p;
  if (typeof repeat_penalty === 'number') options.repeat_penalty = repeat_penalty;
  if (Array.isArray(stop) && stop.length > 0) options.stop = stop;

  const body = {
    model,
    messages: messages || [{ role: 'user', content: prompt }],
    stream: false,
    options,
    logprobs: true,
    top_logprobs: top_logprobs,
  };

  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Ollama error (${resp.status}): ${text}`);
  }

  return resp.json();
}

// Normalize Ollama native logprobs into our standard shape
function normalizeOllamaLogprobs(ollamaResponse) {
  // Ollama native /api/chat returns logprobs as an array of token entries
  // Each entry: { token, logprob, top_logprobs: [{token, logprob}, ...] }
  const logprobs = ollamaResponse?.logprobs;
  if (!Array.isArray(logprobs) || logprobs.length === 0) return [];

  return logprobs.map((entry) => normalizeTokenEntry({
    token: entry.token,
    logprob: entry.logprob,
    top_logprobs: entry.top_logprobs || [],
  }));
}

// --- LM Studio /v1/responses helpers ---

async function lmstudioResponsesWithLogprobs({ origin, model, prompt, messages, temperature, top_logprobs, max_output_tokens, seed, top_p, repeat_penalty, stop }) {
  const url = `${origin}/v1/responses`;
  // /v1/responses accepts `input` as a string or an array of message objects
  const input = messages || prompt;
  const body = {
    model,
    input,
    temperature,
    max_output_tokens,
    top_logprobs,
    include: ['message.output_text.logprobs'],
  };
  if (typeof seed === 'number') body.seed = seed;
  if (typeof top_p === 'number') body.top_p = top_p;
  if (typeof repeat_penalty === 'number') body.repetition_penalty = repeat_penalty;
  if (Array.isArray(stop) && stop.length > 0) body.stop = stop;

  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`LM Studio error (${resp.status}): ${text}`);
  }

  return resp.json();
}

// Normalize LM Studio /v1/responses logprobs into our standard shape
function normalizeLmstudioLogprobs(responsesData) {
  // Shape: output[0].content[0].logprobs[] where each entry has
  // { token, logprob, bytes, top_logprobs: [{token, logprob, bytes}] }
  const output = responsesData?.output?.[0];
  const content = output?.content?.[0];
  const logprobs = content?.logprobs;
  if (!Array.isArray(logprobs) || logprobs.length === 0) return [];

  return logprobs.map((entry) => normalizeTokenEntry({
    token: entry.token,
    logprob: entry.logprob,
    top_logprobs: entry.top_logprobs || [],
  }));
}

function extractLmstudioResponseText(responsesData) {
  const output = responsesData?.output?.[0];
  const content = output?.content?.[0];
  return content?.text || '';
}

// Extract token logprob entries from an OpenAI-format chat completions response
function extractTokenEntries(response) {
  const choice = response?.choices?.[0];
  if (!choice) return [];
  const content = choice?.logprobs?.content;
  if (Array.isArray(content) && content.length > 0) {
    return content;
  }
  return [];
}

// Tell the frontend whether an env key is available (so it can show a hint)
app.get('/api/has-env-key', (_req, res) => {
  res.json({ hasKey: !!envOpenAIKey });
});

// Serve pre-scanned supported model list (from supported.json)
app.get('/api/supported-models', (_req, res) => {
  const data = loadSupportedModels();
  if (!data) {
    return res.json({ available: false, message: 'No supported.json found. Run: node scan-models.js' });
  }
  res.json({ available: true, ...data });
});

// Use `lms ls --json --llm` for rich LM Studio metadata
const { execSync } = require('child_process');

function lmstudioModelsFromCli() {
  try {
    const output = execSync('lms ls --json --llm', { encoding: 'utf8', timeout: 15000, stdio: ['pipe', 'pipe', 'pipe'] });
    const models = JSON.parse(output);
    if (!Array.isArray(models) || models.length === 0) return null;
    return models
      .filter((m) => m.type === 'llm' || m.type === 'vlm')
      .map((m) => ({
        id: m.modelKey || m.id,
        parameter_size: m.paramsString || '',
        quantization: m.quantization?.name || '',
        size_bytes: m.sizeBytes || null,
        size_display: m.sizeBytes ? formatBytes(m.sizeBytes) : '',
        family: m.architecture || '',
        format: m.format || '',
      }))
      .sort((a, b) => a.id.localeCompare(b.id));
  } catch {
    return null;
  }
}

function formatBytes(bytes) {
  if (typeof bytes !== 'number') return '';
  if (bytes >= 1e9) return (bytes / 1e9).toFixed(1) + ' GB';
  if (bytes >= 1e6) return (bytes / 1e6).toFixed(1) + ' MB';
  return bytes + ' B';
}

// List available models from the provider
app.post('/api/models', async (req, res) => {
  try {
    const { provider: providerConfig } = req.body || {};
    const { provider } = providerConfig || {};

    if (provider === 'ollama') {
      const origin = resolveBaseOrigin(providerConfig);
      const resp = await fetch(`${origin}/api/tags`);
      if (!resp.ok) throw new Error(`Ollama returned ${resp.status}`);
      const data = await resp.json();
      const models = (data.models || [])
        .map((m) => ({
          id: m.name || m.model,
          parameter_size: m.details?.parameter_size || '',
          quantization: m.details?.quantization_level || '',
          size_bytes: m.size || null,
          size_display: m.size ? formatBytes(m.size) : '',
          family: m.details?.family || '',
          format: m.details?.format || '',
        }))
        .sort((a, b) => a.id.localeCompare(b.id));
      return res.json({ models });
    }

    if (provider === 'lmstudio') {
      // Try lms CLI first for rich metadata
      const cliModels = lmstudioModelsFromCli();
      if (cliModels) return res.json({ models: cliModels });

      // Fall back to API (no metadata)
      const client = makeClient(providerConfig);
      const list = await client.models.list();
      const models = [];
      for await (const model of list) {
        models.push({ id: model.id });
      }
      models.sort((a, b) => a.id.localeCompare(b.id));
      return res.json({ models });
    }

    // OpenAI: use the OpenAI SDK
    const client = makeClient(providerConfig);
    const list = await client.models.list();
    const models = [];
    for await (const model of list) {
      models.push({ id: model.id, owned_by: model.owned_by || '' });
    }
    models.sort((a, b) => a.id.localeCompare(b.id));
    res.json({ models });
  } catch (error) {
    console.error('API error in /api/models:', error);
    res.status(500).json({ error: error?.message || 'Could not fetch models from provider' });
  }
});

// Unload a model from memory
app.post('/api/unload', async (req, res) => {
  try {
    const { model, provider: providerConfig } = req.body || {};
    const { provider } = providerConfig || {};

    if (!model) {
      return res.status(400).json({ error: 'Model name is required to unload.' });
    }

    if (provider === 'ollama') {
      const origin = resolveBaseOrigin(providerConfig);
      const resp = await fetch(`${origin}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ model, keep_alive: 0 }),
      });
      if (!resp.ok) {
        const text = await resp.text();
        throw new Error(`Ollama unload failed (${resp.status}): ${text}`);
      }
      const data = await resp.json();
      return res.json({ success: true, detail: data });
    }

    if (provider === 'lmstudio') {
      const origin = resolveBaseOrigin(providerConfig);
      const resp = await fetch(`${origin}/api/v1/models/unload`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ instance_id: model }),
      });
      if (!resp.ok) {
        const text = await resp.text();
        throw new Error(`LM Studio unload failed (${resp.status}): ${text}`);
      }
      const data = await resp.json();
      return res.json({ success: true, detail: data });
    }

    return res.status(400).json({ error: 'Unloading is only supported for local providers (LM Studio, Ollama).' });
  } catch (error) {
    console.error('API error in /api/unload:', error);
    res.status(500).json({ error: error?.message || 'Failed to unload model' });
  }
});

app.post('/api/next-token', async (req, res) => {
  try {
    const {
      prompt,
      model = 'gpt-4.1-mini',
      temperature = 0,
      top_logprobs = 5,
      seed,
      top_p,
      repeat_penalty,
      stop,
      provider: providerConfig,
    } = req.body || {};

    const parsedSeed = typeof seed === 'number' ? seed : undefined;
    const parsedTopP = typeof top_p === 'number' ? top_p : undefined;
    const parsedRepeatPenalty = typeof repeat_penalty === 'number' ? repeat_penalty : undefined;
    const parsedStop = Array.isArray(stop) && stop.length > 0 ? stop : undefined;

    if (!prompt || typeof prompt !== 'string') {
      return res.status(400).json({ error: '"prompt" is required and must be a string.' });
    }

    const { provider } = providerConfig || {};

    if (provider === 'ollama') {
      const origin = resolveBaseOrigin(providerConfig);
      const ollamaResp = await ollamaChatWithLogprobs({
        origin, model, prompt, temperature, top_logprobs, max_output_tokens: 1,
        seed: parsedSeed, top_p: parsedTopP, repeat_penalty: parsedRepeatPenalty, stop: parsedStop,
      });
      const tokenEntries = normalizeOllamaLogprobs(ollamaResp);
      const first = tokenEntries[0];
      if (!first) {
        return res.status(500).json({
          error: 'No logprobs returned. Make sure you are running Ollama v0.12.11+ which supports logprobs via the native API.',
          raw_response: ollamaResp,
        });
      }
      return res.json({
        prompt,
        generated_token: first.token,
        generated_token_probability: first.probability,
        candidates: first.top_alternatives,
        raw_response: ollamaResp,
      });
    }

    if (provider === 'lmstudio') {
      const origin = resolveBaseOrigin(providerConfig);
      const lmsResp = await lmstudioResponsesWithLogprobs({
        origin, model, prompt, temperature, top_logprobs, max_output_tokens: 1,
        seed: parsedSeed, top_p: parsedTopP, repeat_penalty: parsedRepeatPenalty, stop: parsedStop,
      });
      const tokenEntries = normalizeLmstudioLogprobs(lmsResp);
      const first = tokenEntries[0];
      if (!first) {
        return res.status(500).json({
          error: 'No logprobs returned from LM Studio /v1/responses endpoint.',
          raw_response: lmsResp,
        });
      }
      return res.json({
        prompt,
        generated_token: first.token,
        generated_token_probability: first.probability,
        candidates: first.top_alternatives,
        raw_response: lmsResp,
      });
    }

    // OpenAI: use OpenAI SDK with /v1/chat/completions
    const client = makeClient(providerConfig);
    const openaiParams = {
      model,
      messages: [{ role: 'user', content: prompt }],
      temperature,
      max_tokens: 1,
      logprobs: true,
      top_logprobs,
    };
    if (parsedSeed !== undefined) openaiParams.seed = parsedSeed;
    if (parsedTopP !== undefined) openaiParams.top_p = parsedTopP;
    if (parsedStop) openaiParams.stop = parsedStop;
    const response = await client.chat.completions.create(openaiParams);

    const entries = extractTokenEntries(response);
    const first = entries[0];

    if (!first) {
      return res.status(500).json({
        error: 'Could not parse token logprobs from API response.',
        raw_response: response,
      });
    }

    const normalized = normalizeTokenEntry(first);
    res.json({
      prompt,
      generated_token: normalized.token,
      generated_token_probability: normalized.probability,
      candidates: normalized.top_alternatives,
      raw_response: response,
    });
  } catch (error) {
    console.error('API error in /api/next-token:', error);
    res.status(500).json({ error: error?.message || 'Unexpected server error' });
  }
});

app.post('/api/token-walk', async (req, res) => {
  try {
    const {
      prompt,
      messages: clientMessages,
      model = 'gpt-4.1-mini',
      temperature = 0,
      top_logprobs = 5,
      max_output_tokens = 80,
      seed,
      top_p,
      repeat_penalty,
      stop,
      provider: providerConfig,
    } = req.body || {};

    const parsedSeed = typeof seed === 'number' ? seed : undefined;
    const parsedTopP = typeof top_p === 'number' ? top_p : undefined;
    const parsedRepeatPenalty = typeof repeat_penalty === 'number' ? repeat_penalty : undefined;
    const parsedStop = Array.isArray(stop) && stop.length > 0 ? stop : undefined;

    // Support both single prompt and multi-turn messages array
    const hasMessages = Array.isArray(clientMessages) && clientMessages.length > 0;
    if (!hasMessages && (!prompt || typeof prompt !== 'string')) {
      return res.status(400).json({ error: '"prompt" or "messages" is required.' });
    }

    const { provider } = providerConfig || {};

    if (provider === 'ollama') {
      const origin = resolveBaseOrigin(providerConfig);
      const ollamaResp = await ollamaChatWithLogprobs({
        origin, model, prompt, messages: hasMessages ? clientMessages : undefined,
        temperature, top_logprobs, max_output_tokens,
        seed: parsedSeed, top_p: parsedTopP, repeat_penalty: parsedRepeatPenalty, stop: parsedStop,
      });
      const tokenEntries = normalizeOllamaLogprobs(ollamaResp);

      if (tokenEntries.length === 0) {
        return res.status(500).json({
          error: 'No logprobs returned. Make sure you are running Ollama v0.12.11+ which supports logprobs via the native API.',
          raw_response: ollamaResp,
        });
      }

      // Derive response_text from tokens — this is the source of truth
      // for exact whitespace, newlines, and formatting
      const outputText = tokenEntries.map(t => t.token).join('');

      return res.json({
        prompt,
        response_text: outputText,
        tokens: tokenEntries,
        token_count: tokenEntries.length,
        raw_response: ollamaResp,
      });
    }

    if (provider === 'lmstudio') {
      const origin = resolveBaseOrigin(providerConfig);
      const lmsResp = await lmstudioResponsesWithLogprobs({
        origin, model, prompt, messages: hasMessages ? clientMessages : undefined,
        temperature, top_logprobs, max_output_tokens,
        seed: parsedSeed, top_p: parsedTopP, repeat_penalty: parsedRepeatPenalty, stop: parsedStop,
      });
      const tokenEntries = normalizeLmstudioLogprobs(lmsResp);

      if (tokenEntries.length === 0) {
        return res.status(500).json({
          error: 'No logprobs returned from LM Studio /v1/responses endpoint.',
          raw_response: lmsResp,
        });
      }

      // Derive response_text from tokens — source of truth for formatting
      const outputText = tokenEntries.map(t => t.token).join('');

      return res.json({
        prompt,
        response_text: outputText,
        tokens: tokenEntries,
        token_count: tokenEntries.length,
        raw_response: lmsResp,
      });
    }

    // OpenAI: use OpenAI SDK
    const client = makeClient(providerConfig);
    const chatMessages = hasMessages ? clientMessages : [{ role: 'user', content: prompt }];
    const openaiParams = {
      model,
      messages: chatMessages,
      temperature,
      max_tokens: max_output_tokens,
      logprobs: true,
      top_logprobs,
    };
    if (parsedSeed !== undefined) openaiParams.seed = parsedSeed;
    if (parsedTopP !== undefined) openaiParams.top_p = parsedTopP;
    if (parsedStop) openaiParams.stop = parsedStop;
    const response = await client.chat.completions.create(openaiParams);

    const tokenEntries = extractTokenEntries(response).map(normalizeTokenEntry);

    if (tokenEntries.length === 0) {
      return res.status(500).json({
        error: 'No token logprobs returned from OpenAI.',
        raw_response: response,
      });
    }

    // Derive response_text from tokens — source of truth for formatting
    const outputText = tokenEntries.map(t => t.token).join('');

    res.json({
      prompt,
      response_text: outputText,
      tokens: tokenEntries,
      token_count: tokenEntries.length,
      raw_response: response,
    });
  } catch (error) {
    console.error('API error in /api/token-walk:', error);
    res.status(500).json({ error: error?.message || 'Unexpected server error' });
  }
});

app.listen(port, () => {
  console.log(`Next Token Explorer (autoregressive token visualizer) running at http://localhost:${port}`);
});
